server:
  port: 9000  # 9000번 포트로 실행

spring:
  application:
    name: demo
    mvc:
      static-path-pattern: /static/**

  datasource:
    platform: mysql
    url: jdbc:mysql://yummy-aws-db1.clxh6sckhw5x.ap-northeast-2.rds.amazonaws.com/UMC?autoReconnect=true
    #url: jdbc:mysql://localhost:3306/local_umc
    # url 형식은 jdbc:mysql://RDS의 EndPoint/내부 DB 스키마명 입니다.
    username: root # 만약 따로 설정하지 않으셨다면 기본값은 admin 입니다
    password: wldnjs0102 # 비밀번호를 입력해주세요!
    driver-class-name: com.mysql.cj.jdbc.Driver
